language: ruby
rvm:
- 2.3.0
services:
- postgresql
before_script:
- psql -c 'create database ensemble_app_test;' -U postgres
before_install:
    openssl aes-256-cbc -K $encrypted_a07f5c7224fe_key -iv $encrypted_a07f5c7224fe_iv -in .env.enc -out .env -d

notifications:
  email: false
